### ISSUE TITLE
Autosplit on lap counter during races + other issues

### ISSUE THREAD

**Issue by hoXyy** [hoXyy/GTAV-AutoSplitter#9]

**Comment by hoXyy** [comment]
Double split after Father/Son

**Comment by hoXyy** [comment]
ok it just doublesplits randomly

**Comment by RakeJyals** [comment]
The lap counter issue can be fixed by detecting if the player is in a race and if so disable the collectable boolean.

**Comment by hoXyy** [comment]
new public release should fix this, so im closing this
